[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
proc-macro2 = { version = "1.0.74" }
quote = { version = "1.0.35" }
syn = { version = "2.0.81" }
smallvec = { version = "1" }
itertools = { version = "0.12" }
thiserror = { version = "2" }
lasso = { version = "0.7.3" }
log = { version = "0.4.33" }
either = { version = "1" }

[package]
name = "lox_rs"
version = "0.1.0"
edition = "2024"


[dependencies]
smallvec.workspace = true
itertools.workspace = true
thiserror.workspace = true
lasso.workspace = true
log.workspace = true
either.workspace = true
nonempty = "0.10"
strum = { version = "0.28.0", features = ["derive"] }
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.11"
annotate-snippets = "0.12.16"

lox_derive = { path = "crates/lox_derive" }
lox_core = { path = "crates/lox_core" }
lexer = { path = "crates/lexer" }
parse = { path = "crates/parse" }

[features]
stress_test_gc = []


[lints.rust]
warnings = "deny"
