[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[dependencies]
lox_core = { path = "../lox_core" }
lexer = { path = "../lexer" }
thiserror.workspace = true
itertools.workspace = true
smallvec.workspace = true
lasso.workspace = true
log.workspace = true
either.workspace = true
ndarray = "0.17"
